[project]
name = "ir-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ir-datasets>=0.5.11",
    "ir-measures>=0.3.7",
    "nltk>=3.9.1",
]
